### ISSUE TITLE
「微」字怪怪的

### ISSUE THREAD

**Issue by jeffchang-git** [max32002/naikaifont#1]
如附圖，regular、light才會這樣

[
![擷取031404](https://user-images.githubusercontent.com/62157023/76655072-77ad2080-65a7-11ea-9210-720631d3faf8.JPG)
](url)

**Comment by max32002** [comment]
![Screen Shot 2020-03-15 at 07 11 03-down](https://user-images.githubusercontent.com/4498233/76692375-8fac9f00-6690-11ea-8013-86f6aaa7b7b7.jpg)

大多的情況都是很難二全其美，在使用 line join=0 可以讓文字在變細時，比較銳利，問題是也可能變成這樣子，開叉了。折衷的方案是使用 join join=1 ，讓筆畫間有渲染的感覺，會略醜，但問題較少 T_T。

**Comment by max32002** [comment]
為了避免類似問題，一再發生，而且系統預設會使用Regular字重，所以已經在 ver 1.29 版之後，把最沒有問題的原版的瀨戶字體搬到Regular 字重。
