### ISSUE TITLE
关于webfont的问题

### ISSUE THREAD

**Issue by lindxzz** [max32002/naikaifont#11]
作者好，请问要使用内海字体NaikaiFont-Bold.woff2版本， webfont的url应该应该怎么样写，非常干虾！

**Comment by max32002** [comment]
```
@font-face {
  font-family: naikaifont;
  src: url(https://cdn.jsdelivr.net/gh/max32002/naikaifont@1.89/webfont/NaikaiFont-Regular.woff2) format("woff2");
}
```

Regular 換成 Bold 即可.

**Comment by lindxzz** [comment]
> ```
> @font-face {
>   font-family: naikaifont;
>   src: url(https://cdn.jsdelivr.net/gh/max32002/naikaifont@1.89/webfont/NaikaiFont-Regular.woff2) format("woff2");
> }
> ```
> 
> Regular 換成 Bold 即可.

我体换了Bold后字体没有生效，但是Regular有效。其他类型的webfont都使用不了

**Comment by max32002** [comment]
font-family 可能需要指派一下, 不一樣的值, 我猜.
