### ISSUE TITLE
「獼」猴的獼少兩撇

### ISSUE THREAD

**Issue by jeffchang-git** [max32002/naikaifont#2]
如附圖
![1585920575973](https://user-images.githubusercontent.com/62157023/78365957-68dbeb80-75f2-11ea-8b55-390fd6f352a9.jpg)

**Comment by max32002** [comment]
原作者，的就已經少了。Q_Q;

**Comment by max32002** [comment]
幫你加好二點了，請下載 ver 1.31。
建議改用「獮猴」。
